classes = {
  0: "background",
  1: "bottled soda",
  2: "cheese",
  3: "chocolate bar",
  4: "cofee",
  5: "condensed milk",
  6: "cooking oil",
  7: "corned beef",
  8: "garlic",
  9: "instant noodles",
  10: "ketchup",
  11: "lemon",
  12: "all purpose cream",
  13: "mayonnaise",
  14: "peanut butter",
  15: "pasta",
  16: "pineapple juice",
  17: "crackers",
  18: "sardines",
  19: "shampoo",
  20: "soap",
  21: "soy sauce",
  22: "toothpaste",
  23: "canned tuna",
  24: "ethyl alcohol"    
}