base_dir: /data/students/gerry/repos/grocery-cv
model:
  model: ${..base_dir}/aiml/pretrained/yolo11x.pt
train:
  data: ${..base_dir}/aiml/coco_grocery.yaml
  epochs: 200 #try for one epoch
  patience: 100
  device: 1
  batch: 16
  workers: 8
  project: grocery-cv-detect-yolox-v3-002
  plots: true
  # augmentations
  copy_paste: 0.1
  mixup: 0.1
  perspective: 0.1
  degrees: -10