base_dir: /data/students/gerry/repos/grocery-cv
model:
  model: ${..base_dir}/aiml/pretrained/yolo11m.pt
train:
  data: ${..base_dir}/aiml/coco_grocery.yaml
  epochs: 100 #try for one epoch
  device: [1]
  workers: 8
  project: grocery-cv-detect-yolom-aug001
  # aug
  hsv_h: 0.3
  hsv_v: 0.9
  degrees: 90
  translate: 0.1
  shear: 90
  perspective: 0.0002
  flipud: 0.5
  fliplr: 0.5